- Problem Statement: Implement a Neural Network Layer

Your task is to implement a simple neural network layer using Python and NumPy. The layer should be capable of performing the forward pass computation, which involves calculating the output of the layer given input data, weights, and biases.

Instructions:

Implement a Python class called Layer_Dense representing a single layer in a neural network.
The class should have:
A constructor (__init__ method) taking two parameters: n_inputs (number of input features) and n_neurons (number of neurons in the layer).
Initialize the weights randomly and the biases to zeros in the constructor.
Implement a forward method that takes inputs as a parameter and computes the output of the layer using matrix multiplication between the inputs, weights, and biases.
Test your implementation:
Create an instance of Layer_Dense with appropriate input and neuron dimensions.
Provide input data (a 2D array) to the layer.
Call the forward method to compute the output of the layer.
Print the output and biases of the layer.

In [3]:
import numpy as np
np.random.seed(0)

X=[[1, 2, 3, 2.5],
   [2, 5, -1, 2],
   [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.1*np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases 

layer1= Layer_Dense(4, 5)  # (input_feature , anyoutputshape1)
layer2= Layer_Dense(5, 2)  # (anyoutputshape1 , anyoutputshape2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print("----")
print(layer2.output)


[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
----
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
